# Generated by Django 2.0.5 on 2018-05-20 06:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='Tag',
        ),
    ]
