# Generated by Django 2.0.5 on 2018-05-22 09:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180520_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[blog.models.min_length_3_validator]),
        ),
    ]
